/**
 * Generate command - generates types and client from schema
 *
 * Issue #22, #23 (watch mode), #24 (client package), #133 (project-local output)
 */

import { Command } from 'commander'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname, basename, join, relative, isAbsolute, sep } from 'path'
import { watch } from 'chokidar'
import { parseSchema } from '../parser/schema-parser.js'
import { toError } from '../utils/errors.js'
import { generateTypes } from '../generator/types-generator.js'
import { generateClient } from '../generator/client-generator.js'
import { generateClientPackage } from '../generator/client-package-generator.js'
import { loadConfig, type GSQConfig } from './init.js'

// =============================================================================
// Constants
// =============================================================================

/** Default schema file, used when neither a flag nor config provides one. */
export const DEFAULT_SCHEMA_FILE = 'schema.gsq.yaml'

/** Default output directory for types/client/index. */
export const DEFAULT_OUTPUT_DIR = 'generated'

/** Sub-directory of the output directory used for the typed client. */
export const DEFAULT_CLIENT_SUBDIR = 'client'

/** Marker that identifies a file as previously generated by gsquery. */
const GENERATED_MARKER = 'Auto-generated by gsquery'

/** Files written by the generator into a target directory. */
const GENERATED_FILENAMES = ['types.ts', 'client.ts', 'index.ts'] as const

// =============================================================================
// Types
// =============================================================================

/**
 * Raw options as parsed from the command line. Every value is optional so it
 * can fall back to gsquery.config.json and then to the built-in defaults.
 */
export interface GenerateCliOptions {
  schema?: string
  output?: string
  clientOutput?: string
  watch?: boolean
  client?: boolean
  force?: boolean
}

export interface GenerateOptions {
  schema: string
  output: string
  /** Typed client output directory. Defaults to `<output>/client`. */
  clientOutput?: string
  watch?: boolean
  client?: boolean
  /** Overwrite files that lack the auto-generated header. */
  force?: boolean
}

export interface GenerateResult {
  success: boolean
  files: string[]
  errors: string[]
  warnings: string[]
}

// =============================================================================
// Option Resolution
// =============================================================================

/**
 * Pick the first non-empty string, or undefined when there is none.
 */
function firstNonEmpty(...values: Array<string | undefined>): string | undefined {
  for (const value of values) {
    if (typeof value === 'string' && value.length > 0) {
      return value
    }
  }
  return undefined
}

/**
 * Resolve generate options from CLI flags, config file, and defaults.
 *
 * Precedence: CLI flag > gsquery.config.json > built-in default.
 */
export function resolveGenerateOptions(
  options: GenerateCliOptions,
  config: GSQConfig | null
): GenerateOptions {
  const schema = firstNonEmpty(options.schema, config?.schemaFile) ?? DEFAULT_SCHEMA_FILE
  const output = firstNonEmpty(options.output, config?.generatedDir) ?? DEFAULT_OUTPUT_DIR
  const clientOutput =
    firstNonEmpty(options.clientOutput, config?.clientDir) ?? join(output, DEFAULT_CLIENT_SUBDIR)

  return {
    schema,
    output,
    clientOutput,
    watch: options.watch,
    client: options.client,
    force: options.force,
  }
}

// =============================================================================
// Index Generator
// =============================================================================

/**
 * Generate index.ts that re-exports types and client
 */
export function generateIndex(): string {
  const lines = [
    '// Auto-generated by gsquery - DO NOT EDIT',
    '',
    "export * from './types.js'",
    "export * from './client.js'",
  ]
  return lines.join('\n') + '\n'
}

// =============================================================================
// File Operations
// =============================================================================

/**
 * Ensure directory exists
 */
function ensureDir(dirPath: string): void {
  if (!existsSync(dirPath)) {
    mkdirSync(dirPath, { recursive: true })
  }
}

/**
 * Write file with directory creation
 */
function writeFile(filePath: string, content: string): void {
  ensureDir(dirname(filePath))
  writeFileSync(filePath, content, 'utf-8')
}

/**
 * Check whether an existing file carries the gsquery auto-generated header.
 * Unreadable files are treated as not generated so they stay protected.
 */
function isGeneratedFile(filePath: string): boolean {
  try {
    return readFileSync(filePath, 'utf-8').includes(GENERATED_MARKER)
  } catch {
    return false
  }
}

/**
 * Collect existing target files that were not produced by gsquery.
 * These must not be overwritten unless --force is passed.
 */
function findProtectedFiles(targets: string[]): string[] {
  return targets.filter(target => existsSync(target) && !isGeneratedFile(target))
}

/**
 * Absolute paths of every file the generator writes into a directory.
 */
function targetPaths(dir: string): string[] {
  return GENERATED_FILENAMES.map(name => resolve(dir, name))
}

/**
 * Format a path for display and for the generated import example:
 * project-relative with POSIX separators, prefixed with './'.
 */
function toProjectPath(absolutePath: string): string {
  const rel = relative(process.cwd(), absolutePath)
  if (rel === '' || isAbsolute(rel)) {
    return absolutePath
  }
  return rel.split(sep).join('/')
}

/**
 * Import specifier the generated docs should show for the client directory.
 */
function toImportSpecifier(absolutePath: string): string {
  const projectPath = toProjectPath(absolutePath)
  if (isAbsolute(projectPath) || projectPath.startsWith('.')) {
    return projectPath
  }
  return `./${projectPath}`
}

// =============================================================================
// Generate Logic
// =============================================================================

/**
 * Run the generate command
 */
export async function runGenerate(options: GenerateOptions): Promise<GenerateResult> {
  const errors: string[] = []
  const warnings: string[] = []
  const files: string[] = []
  
  // Resolve paths
  const schemaPath = resolve(process.cwd(), options.schema)
  const outputDir = resolve(process.cwd(), options.output)
  const clientOutputDir = resolve(
    process.cwd(),
    options.clientOutput ?? join(options.output, DEFAULT_CLIENT_SUBDIR)
  )

  // Check schema file exists
  if (!existsSync(schemaPath)) {
    return {
      success: false,
      files: [],
      errors: [`Schema file not found: ${schemaPath}`],
      warnings: [],
    }
  }
  
  // Read schema file
  let schemaContent: string
  try {
    schemaContent = readFileSync(schemaPath, 'utf-8')
  } catch (err) {
    const error = toError(err)
    return {
      success: false,
      files: [],
      errors: [`Failed to read schema file: ${error.message}`],
      warnings: [],
    }
  }
  
  // Parse schema
  const parseResult = parseSchema(schemaContent)
  
  if (!parseResult.success || !parseResult.schema) {
    return {
      success: false,
      files: [],
      errors: parseResult.errors.map(e => e.message),
      warnings: [],
    }
  }
  
  // Collect parse warnings
  if (parseResult.errors.length > 0) {
    for (const err of parseResult.errors) {
      warnings.push(err.message)
    }
  }
  
  const schema = parseResult.schema

  // Refuse to clobber files that gsquery did not generate
  if (!options.force) {
    const candidates = [
      ...targetPaths(outputDir),
      ...(options.client ? targetPaths(clientOutputDir) : []),
    ]
    const protectedFiles = findProtectedFiles(candidates)

    if (protectedFiles.length > 0) {
      return {
        success: false,
        files: [],
        errors: protectedFiles.map(
          file =>
            `Refusing to overwrite ${toProjectPath(file)}: it is missing the ` +
            `"${GENERATED_MARKER}" header. Use --force to overwrite.`
        ),
        warnings,
      }
    }
  }

  // Generate types
  try {
    const typesContent = generateTypes(schema)
    const typesPath = resolve(outputDir, 'types.ts')
    writeFile(typesPath, typesContent)
    files.push('types.ts')
  } catch (err) {
    const error = toError(err)
    return {
      success: false,
      files,
      errors: [...errors, `Failed to generate types: ${error.message}`],
      warnings,
    }
  }
  
  // Generate client
  try {
    const clientContent = generateClient(schema)
    const clientPath = resolve(outputDir, 'client.ts')
    writeFile(clientPath, clientContent)
    files.push('client.ts')
  } catch (err) {
    const error = toError(err)
    return {
      success: false,
      files,
      errors: [...errors, `Failed to generate client: ${error.message}`],
      warnings,
    }
  }
  
  // Generate index
  try {
    const indexContent = generateIndex()
    const indexPath = resolve(outputDir, 'index.ts')
    writeFile(indexPath, indexContent)
    files.push('index.ts')
  } catch (err) {
    const error = toError(err)
    return {
      success: false,
      files,
      errors: [...errors, `Failed to generate index: ${error.message}`],
      warnings,
    }
  }
  
  // Generate typed client into the project (--client option)
  if (options.client) {
    try {
      const clientFiles = generateClientPackage(schema, {
        importPath: toImportSpecifier(clientOutputDir),
      })

      for (const [filename, content] of Object.entries(clientFiles)) {
        writeFile(resolve(clientOutputDir, filename), content)
      }
      files.push(toProjectPath(clientOutputDir))
    } catch (err) {
      const error = toError(err)
      return {
        success: false,
        files,
        errors: [...errors, `Failed to generate client: ${error.message}`],
        warnings,
      }
    }
  }

  return {
    success: true,
    files,
    errors,
    warnings,
  }
}

// =============================================================================
// Utilities
// =============================================================================

/**
 * Format current time as [HH:MM:SS]
 */
function formatTimestamp(): string {
  const now = new Date()
  const hours = String(now.getHours()).padStart(2, '0')
  const minutes = String(now.getMinutes()).padStart(2, '0')
  const seconds = String(now.getSeconds()).padStart(2, '0')
  return `[${hours}:${minutes}:${seconds}]`
}

/**
 * Run generate and print results (used by both initial run and watch)
 */
async function runAndPrint(options: GenerateOptions): Promise<boolean> {
  const result = await runGenerate(options)
  
  if (!result.success) {
    console.error('❌ Generation failed:')
    for (const error of result.errors) {
      console.error(`   ${error}`)
    }
    return false
  }
  
  // Show warnings if any
  if (result.warnings.length > 0) {
    console.log('⚠️  Warnings:')
    for (const warning of result.warnings) {
      console.log(`   ${warning}`)
    }
  }
  
  console.log(`✅ Generated ${result.files.join(', ')}`)
  return true
}

/**
 * Start watching schema file for changes
 */
async function startWatch(options: GenerateOptions): Promise<void> {
  const schemaPath = resolve(process.cwd(), options.schema)
  const schemaName = basename(schemaPath)
  
  console.log('👀 Watching for changes...')
  console.log('')
  
  const watcher = watch(schemaPath, {
    persistent: true,
    ignoreInitial: true,
  })
  
  // Debounce to avoid multiple rapid triggers
  let debounceTimer: NodeJS.Timeout | null = null
  
  watcher.on('change', () => {
    if (debounceTimer) {
      clearTimeout(debounceTimer)
    }
    
    debounceTimer = setTimeout(async () => {
      const startTime = performance.now()
      console.log(`${formatTimestamp()} ${schemaName} changed`)
      
      try {
        const success = await runAndPrint(options)
        const elapsed = Math.round(performance.now() - startTime)
        
        if (success) {
          console.log(`   Regenerated in ${elapsed}ms`)
        }
      } catch (err) {
        const error = toError(err)
        console.error(`❌ Error: ${error.message}`)
      }
      console.log('')
    }, 100) // 100ms debounce
  })
  
  watcher.on('error', (err: unknown) => {
    const error = err instanceof Error ? err : new Error(String(err))
    console.error(`❌ Watcher error: ${error.message}`)
  })
  
  // Handle Ctrl+C gracefully
  const cleanup = () => {
    console.log('')
    console.log('👋 Stopping watch mode...')
    watcher.close()
    process.exit(0)
  }
  
  process.on('SIGINT', cleanup)
  process.on('SIGTERM', cleanup)
  
  // Keep process alive
  await new Promise(() => {})
}

// =============================================================================
// CLI Command
// =============================================================================

export const generateCommand = new Command('generate')
  .description('Generate types and client from schema')
  .option('-s, --schema <path>', `Schema file path (default: ${DEFAULT_SCHEMA_FILE})`)
  .option('-o, --output <path>', `Output directory (default: ${DEFAULT_OUTPUT_DIR})`)
  .option('-w, --watch', 'Watch schema file for changes and regenerate')
  .option('-c, --client', 'Also generate a typed client into the project')
  .option(
    '--client-output <path>',
    `Typed client output directory (default: <output>/${DEFAULT_CLIENT_SUBDIR})`
  )
  .option('-f, --force', 'Overwrite files that lack the auto-generated header')
  .action(async (cliOptions: GenerateCliOptions) => {
    let config: GSQConfig | null = null
    try {
      config = loadConfig()
    } catch (err) {
      console.warn(`⚠️  ${toError(err).message}`)
    }

    const options = resolveGenerateOptions(cliOptions, config)

    console.log('🔧 Generating from schema...')
    console.log(`   Schema: ${options.schema}`)
    console.log(`   Output: ${options.output}`)
    if (options.client) {
      console.log(`   Client: ${options.clientOutput}`)
    }
    console.log('')

    // Initial generation
    const success = await runAndPrint(options)
    
    if (!success && !options.watch) {
      process.exit(1)
    }
    
    // Watch mode
    if (options.watch) {
      console.log('')
      await startWatch(options)
    } else {
      console.log('')
      console.log('🎉 Done!')
    }
  })
