/**
 * Client Package Generator
 *
 * Generates files for @gsquery/client package.
 * Issue #24
 */

import type { SchemaAST, TableAST } from '../parser/types.js'
import { escapeStringLiteral } from '../utils/sanitize.js'

// =============================================================================
// Constants
// =============================================================================

const HEADER = '// Auto-generated by gsquery - DO NOT EDIT'

// =============================================================================
// Type Mapping
// =============================================================================

/**
 * Map schema types to TypeScript types
 */
function mapType(schemaType: string): string {
  switch (schemaType) {
    case 'string':
      return 'string'
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'datetime':
      return 'Date'
    default:
      // Enum or custom type - keep as-is
      return schemaType
  }
}

// =============================================================================
// Types File Generation
// =============================================================================

/**
 * Generate types.ts for @gsquery/client/generated
 */
export function generateClientTypes(ast: SchemaAST): string {
  const lines: string[] = []

  lines.push(HEADER)
  lines.push('')

  // Import RowWithId
  lines.push("import type { RowWithId } from '@gsquery/core'")
  lines.push('')

  // Enums
  const enumNames = Object.keys(ast.enums).sort()
  for (const name of enumNames) {
    const enumAst = ast.enums[name]
    const values = enumAst.values.map(v => `'${escapeStringLiteral(v)}'`).join(' | ')
    lines.push(`export type ${name} = ${values}`)
  }

  if (enumNames.length > 0) {
    lines.push('')
  }

  // Interfaces
  const tableNames = Object.keys(ast.tables).sort()
  for (let i = 0; i < tableNames.length; i++) {
    if (i > 0) lines.push('')

    const table = ast.tables[tableNames[i]]
    lines.push(`export interface ${table.name} extends RowWithId {`)

    for (const field of table.fields) {
      const optionalMark = field.optional ? '?' : ''
      const tsType = mapType(field.type)
      lines.push(`  ${field.name}${optionalMark}: ${tsType}`)
    }

    lines.push('}')
  }

  // Tables type
  if (tableNames.length > 0) {
    lines.push('')
    lines.push('export type Tables = {')
    for (const name of tableNames) {
      lines.push(`  ${name}: ${name}`)
    }
    lines.push('}')
  }

  return lines.join('\n') + '\n'
}

// =============================================================================
// Schema File Generation
// =============================================================================

/**
 * Generate schema object for runtime
 */
function generateTableSchema(table: TableAST): string {
  const columns = table.fields.map(f => `'${escapeStringLiteral(f.name)}'`).join(', ')
  const parts = [`columns: [${columns}] as const`]

  if (table.mapTo) {
    parts.push(`sheetName: '${escapeStringLiteral(table.mapTo)}'`)
  }

  return `{ ${parts.join(', ')} }`
}

/**
 * Generate client.ts for @gsquery/client/generated
 */
export function generateClientCode(ast: SchemaAST): string {
  const lines: string[] = []
  const tableNames = Object.keys(ast.tables).sort()

  lines.push(HEADER)
  lines.push('')

  // Imports
  lines.push("import { createClientFactory, type GeneratedSchema } from '@gsquery/client'")
  lines.push("import type { Tables } from './types.js'")
  lines.push('')

  // Schema constant
  lines.push('export const schema: GeneratedSchema = {')
  lines.push('  tables: {')

  for (let i = 0; i < tableNames.length; i++) {
    const name = tableNames[i]
    const comma = i < tableNames.length - 1 ? ',' : ''
    lines.push(`    ${name}: ${generateTableSchema(ast.tables[name])}${comma}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')

  // createClient function
  lines.push('/**')
  lines.push(' * Create a typed database client')
  lines.push(' * ')
  lines.push(' * @example')
  lines.push(' * ```ts')
  lines.push(" * import { createClient } from '@gsquery/client/generated'")
  lines.push(' * ')
  lines.push(" * const db = createClient({ spreadsheetId: 'your-spreadsheet-id' })")
  lines.push(' * ')
  lines.push(' * // Type-safe API')
  if (tableNames.length > 0) {
    const exampleTable = escapeStringLiteral(tableNames[0])
    lines.push(` * const items = db.from('${exampleTable}').findAll()`)
    lines.push(` * const item = db.from('${exampleTable}').query().where('id', '=', 1).first()`)
  }
  lines.push(' * ```')
  lines.push(' */')
  lines.push('export const createClient = createClientFactory<Tables>(schema)')
  lines.push('')

  // createTestClient for testing
  lines.push('/**')
  lines.push(' * Create a mock client for testing')
  lines.push(' */')
  lines.push('export function createTestClient() {')
  lines.push('  return createClient({ mock: true })')
  lines.push('}')

  return lines.join('\n') + '\n'
}

// =============================================================================
// Index File Generation
// =============================================================================

/**
 * Generate index.ts for @gsquery/client/generated
 */
export function generateClientIndex(): string {
  const lines: string[] = []

  lines.push(HEADER)
  lines.push('')
  lines.push("export * from './types.js'")
  lines.push("export * from './client.js'")
  lines.push('')
  lines.push('// Re-export useful types from @gsquery/core')
  lines.push("export type { SheetsDB, TableHandle, RowWithId, DataStore } from '@gsquery/core'")

  return lines.join('\n') + '\n'
}

// =============================================================================
// Main Export
// =============================================================================

export interface ClientPackageFiles {
  'types.ts': string
  'client.ts': string
  'index.ts': string
}

/**
 * Generate all files for @gsquery/client/generated
 */
export function generateClientPackage(ast: SchemaAST): ClientPackageFiles {
  return {
    'types.ts': generateClientTypes(ast),
    'client.ts': generateClientCode(ast),
    'index.ts': generateClientIndex()
  }
}
