/**
 * Client Generator - generates DB client from AST
 * 
 * Issue #21
 */

import type { SchemaAST, TableAST } from '../parser/types.js'

// =============================================================================
// Constants
// =============================================================================

const HEADER = '// Auto-generated by gsquery - DO NOT EDIT'

// =============================================================================
// Import Generation
// =============================================================================

/**
 * Generate library imports
 */
function generateLibraryImport(hasTables: boolean): string {
  if (!hasTables) {
    return "import { createSheetsDB, MockAdapter } from '@gsquery/core'"
  }
  return "import { createSheetsDB, MockAdapter, DataStore } from '@gsquery/core'"
}

/**
 * Generate type imports from ./types
 */
function generateTypeImport(tableNames: string[]): string {
  if (tableNames.length === 0) return ''
  const sorted = [...tableNames].sort()
  return `import type { ${sorted.join(', ')} } from './types'`
}

// =============================================================================
// Tables Type Generation
// =============================================================================

/**
 * Generate Tables type alias
 */
function generateTablesType(tableNames: string[]): string {
  if (tableNames.length === 0) {
    return 'export type Tables = {}'
  }
  
  const sorted = [...tableNames].sort()
  const lines = ['export type Tables = {']
  for (const name of sorted) {
    lines.push(`  ${name}: ${name}`)
  }
  lines.push('}')
  
  return lines.join('\n')
}

// =============================================================================
// Schema Object Generation
// =============================================================================

/**
 * Generate column names array for a table
 */
function generateColumns(table: TableAST): string {
  const columns = table.fields.map(f => `'${f.name}'`).join(', ')
  return `{ columns: [${columns}] as const }`
}

/**
 * Generate schema constant
 */
function generateSchema(tables: Record<string, TableAST>): string {
  const tableNames = Object.keys(tables).sort()
  
  if (tableNames.length === 0) {
    return `export const schema = {\n  tables: {}\n} as const`
  }
  
  const lines = ['export const schema = {', '  tables: {']
  
  for (let i = 0; i < tableNames.length; i++) {
    const name = tableNames[i]
    const comma = i < tableNames.length - 1 ? ',' : ''
    lines.push(`    ${name}: ${generateColumns(tables[name])}${comma}`)
  }
  
  lines.push('  }')
  lines.push('} as const')
  
  return lines.join('\n')
}

// =============================================================================
// Factory Function Generation
// =============================================================================

/**
 * Generate createDB factory function
 */
function generateCreateDB(tableNames: string[]): string {
  if (tableNames.length === 0) {
    return `export function createDB(stores: {}) {
  return createSheetsDB<Tables>({
    config: schema,
    stores
  })
}`
  }
  
  const sorted = [...tableNames].sort()
  const storeParams = sorted.map(name => `  ${name}: DataStore<${name}>`).join('\n')
  
  return `export function createDB(stores: {
${storeParams}
}) {
  return createSheetsDB<Tables>({
    config: schema,
    stores
  })
}`
}

/**
 * Generate createTestDB helper function
 */
function generateCreateTestDB(tableNames: string[]): string {
  if (tableNames.length === 0) {
    return `export function createTestDB() {
  return createDB({})
}`
  }
  
  const sorted = [...tableNames].sort()
  const adapters = sorted.map(name => `    ${name}: new MockAdapter<${name}>()`).join(',\n')
  
  return `export function createTestDB() {
  return createDB({
${adapters}
  })
}`
}

// =============================================================================
// Main Entry Point
// =============================================================================

/**
 * Generate client code from schema AST
 */
export function generateClient(ast: SchemaAST): string {
  const tableNames = Object.keys(ast.tables)
  const hasTables = tableNames.length > 0
  
  const lines: string[] = []
  
  // Header
  lines.push(HEADER)
  lines.push('')
  
  // Imports
  lines.push(generateLibraryImport(hasTables))
  const typeImport = generateTypeImport(tableNames)
  if (typeImport) {
    lines.push(typeImport)
  }
  lines.push('')
  
  // Tables type
  lines.push(generateTablesType(tableNames))
  lines.push('')
  
  // Schema constant
  lines.push(generateSchema(ast.tables))
  lines.push('')
  
  // createDB function
  lines.push(generateCreateDB(tableNames))
  lines.push('')
  
  // createTestDB function
  lines.push(generateCreateTestDB(tableNames))
  
  return lines.join('\n')
}
