/**
 * ERD generator - renders a parsed schema as a Mermaid erDiagram
 *
 * Issue #224
 *
 * Relationship edges come exclusively from declared `@relation(Table)`
 * attributes. Foreign keys are never inferred from naming convention: a
 * silently wrong diagram is worse than one with no edges at all.
 */

import type { SchemaAST, TableAST, FieldAST } from '../parser/types.js'

// =============================================================================
// Constants
// =============================================================================

/** Marker that identifies a file as previously generated by gsquery. */
const HEADER = '<!-- Auto-generated by gsquery - DO NOT EDIT -->'

/** Indent inside the `erDiagram` block. */
const INDENT = '    '

// =============================================================================
// Types
// =============================================================================

export interface ErdResult {
  /** Complete markdown document, mermaid fence included. */
  diagram: string
  /** Number of rendered relationship edges. Zero means no `@relation` was declared. */
  relationCount: number
}

// =============================================================================
// Field Predicates
// =============================================================================

/**
 * Relation target table declared by `@relation(Table)`, or null.
 *
 * The parser never splits attribute arguments on commas, so `args[0]` is the
 * only meaningful slot.
 */
function relationTarget(field: FieldAST): string | null {
  const attr = field.attributes.find(a => a.name === 'relation')
  if (!attr || typeof attr.args[0] !== 'string' || attr.args[0].length === 0) return null
  return attr.args[0]
}

/** Whether the field carries a field-level `@unique`. */
function isUnique(field: FieldAST): boolean {
  return field.attributes.some(a => a.name === 'unique')
}

/**
 * Key markers for the attribute line.
 *
 * Only field-level `@unique` yields UK -- a composite `unique:` block makes the
 * combination unique, not the individual columns, so marking them would lie.
 */
function keyMarkers(field: FieldAST): string {
  const keys: string[] = []
  if (field.name === 'id') keys.push('PK')
  if (relationTarget(field)) keys.push('FK')
  if (isUnique(field)) keys.push('UK')
  return keys.join(', ')
}

/**
 * Trailing comment for the attribute line.
 *
 * Mermaid attribute types cannot express optionality and have no enum concept,
 * so both are folded into the quoted comment.
 */
function attributeComment(field: FieldAST, enums: SchemaAST['enums']): string {
  const parts: string[] = []
  if (field.optional) parts.push('?')

  const enumDef = enums[field.type]
  if (enumDef) parts.push(enumDef.values.join('|'))

  if (parts.length === 0) return ''
  return `"${escapeComment(parts.join(' '))}"`
}

/** Keep a comment closed: enum values come from YAML and may contain quotes. */
function escapeComment(value: string): string {
  return value.replace(/"/g, "'")
}

// =============================================================================
// Rendering
// =============================================================================

/** One attribute line: `type name [PK, FK, UK] ["comment"]`. */
function attributeLine(field: FieldAST, enums: SchemaAST['enums']): string {
  const parts = [field.type, field.name, keyMarkers(field), attributeComment(field, enums)]
  return `${INDENT}${INDENT}${parts.filter(p => p.length > 0).join(' ')}`
}

/** One entity block, preceded by a sheet-name comment when the table is mapped. */
function entityBlock(table: TableAST, enums: SchemaAST['enums']): string[] {
  const lines: string[] = []
  if (table.mapTo) {
    lines.push(`${INDENT}%% ${table.name} -> sheet "${escapeComment(table.mapTo)}"`)
  }
  lines.push(`${INDENT}${table.name} {`)
  for (const field of table.fields) {
    lines.push(attributeLine(field, enums))
  }
  lines.push(`${INDENT}}`)
  return lines
}

/**
 * Cardinality derived from the foreign key's shape.
 *
 * An array FK holds many targets, so it is many-to-many; a unique FK can point
 * at a given row only once, so it is one-to-one. Array wins over unique, which
 * wins over optional.
 */
function cardinality(field: FieldAST): string {
  if (field.type.endsWith('[]')) return '}o--o{'
  if (isUnique(field)) return '||--||'
  if (field.optional) return '|o--o{'
  return '||--o{'
}

/**
 * One relationship line per declared `@relation`.
 *
 * Mermaid requires a label on every edge; the foreign key field name is used,
 * which also disambiguates two relations between the same pair of tables.
 */
function relationshipLines(ast: SchemaAST): string[] {
  const lines: string[] = []
  for (const table of Object.values(ast.tables)) {
    for (const field of table.fields) {
      const target = relationTarget(field)
      // Validation rejects unknown targets, but the renderer may run on an AST
      // that only carries warnings -- skip rather than emit a phantom entity.
      if (!target || !ast.tables[target]) continue
      lines.push(`${INDENT}${target} ${cardinality(field)} ${table.name} : "${field.name}"`)
    }
  }
  return lines
}

/**
 * Render a schema as a Mermaid ER diagram wrapped in a markdown document.
 *
 * @param ast - Parsed schema
 * @returns The markdown document and the number of rendered edges
 *
 * @example
 * ```ts
 * const { diagram, relationCount } = generateErd(schema)
 * if (relationCount === 0) console.error('no @relation declared')
 * ```
 */
export function generateErd(ast: SchemaAST): ErdResult {
  const body: string[] = []
  for (const table of Object.values(ast.tables)) {
    body.push(...entityBlock(table, ast.enums))
  }

  const relations = relationshipLines(ast)
  body.push(...relations)

  const diagram = [HEADER, '', '```mermaid', 'erDiagram', ...body, '```', ''].join('\n')

  return { diagram, relationCount: relations.length }
}
