/**
 * Types Generator - generates TypeScript types from AST
 * 
 * Issue #20
 */

import type { SchemaAST, EnumAST, TableAST, FieldAST } from '../parser/types.js'
import { escapeStringLiteral } from '../utils/sanitize.js'
import { mapType } from './type-mapping.js'

// =============================================================================
// Constants
// =============================================================================

const HEADER = '// Auto-generated by gsquery - DO NOT EDIT'

// =============================================================================
// Enum Generation
// =============================================================================

/**
 * Generate TypeScript union type for an enum
 * 
 * @example
 * export type Role = 'USER' | 'ADMIN'
 */
function generateEnum(enumAst: EnumAST): string {
  const values = enumAst.values.map(v => `'${escapeStringLiteral(v)}'`).join(' | ')
  return `export type ${enumAst.name} = ${values}`
}

// =============================================================================
// Interface Generation
// =============================================================================

/**
 * Generate a single field line
 * 
 * @example
 * "  name: string"
 * "  nickname?: string"
 */
function generateField(field: FieldAST): string {
  const optionalMark = field.optional ? '?' : ''
  const tsType = mapType(field.type)
  return `  ${field.name}${optionalMark}: ${tsType}`
}

/**
 * Generate TypeScript interface for a table
 * 
 * Includes index signature [key: string]: unknown for Row compatibility
 * 
 * @example
 * export interface User {
 *   [key: string]: unknown
 *   id: string
 *   name: string
 * }
 */
function generateInterface(table: TableAST): string {
  const indexSig = '  [key: string]: unknown'
  const fields = table.fields.map(generateField).join('\n')
  return `export interface ${table.name} {\n${indexSig}\n${fields}\n}`
}

// =============================================================================
// Main Entry Point
// =============================================================================

/**
 * Generate TypeScript types from schema AST
 */
export function generateTypes(ast: SchemaAST): string {
  const lines: string[] = []
  
  // Header
  lines.push(HEADER)
  lines.push('')
  
  // Enums (before interfaces so they can be referenced)
  const enumNames = Object.keys(ast.enums).sort()
  for (const name of enumNames) {
    lines.push(generateEnum(ast.enums[name]))
  }
  
  // Add spacing between enums and interfaces
  if (enumNames.length > 0 && Object.keys(ast.tables).length > 0) {
    lines.push('')
  }
  
  // Interfaces
  const tableNames = Object.keys(ast.tables).sort()
  for (let i = 0; i < tableNames.length; i++) {
    if (i > 0) lines.push('')
    lines.push(generateInterface(ast.tables[tableNames[i]]))
  }
  
  return lines.join('\n') + '\n'
}
