/**
 * Client Generator Tests
 * 
 * Issue #21
 */

import { describe, it, expect } from 'vitest'
import { generateClient } from '../../src/generator/client-generator.js'
import type { SchemaAST } from '../../src/parser/types.js'

describe('generateClient', () => {
  // =========================================================================
  // Header
  // =========================================================================
  
  describe('header', () => {
    it('should include auto-generated warning comment', () => {
      const ast: SchemaAST = { enums: {}, tables: {} }
      const result = generateClient(ast)
      
      expect(result).toContain('// Auto-generated by gsquery - DO NOT EDIT')
    })
  })
  
  // =========================================================================
  // Imports
  // =========================================================================
  
  describe('imports', () => {
    it('should import createSheetsDB, MockAdapter, and DataStore from gas-sheets-query', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain("import { createSheetsDB, MockAdapter, DataStore, Row } from '@gsquery/core'")
    })
    
    it('should import types from ./types', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain("import type { User } from './types.js'")
    })
    
    it('should import multiple types sorted alphabetically', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Post: {
            name: 'Post',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          },
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain("import type { Post, User } from './types.js'")
    })
    
    it('should not import types for empty schema', () => {
      const ast: SchemaAST = { enums: {}, tables: {} }
      const result = generateClient(ast)
      
      expect(result).not.toContain("import type")
    })
  })
  
  // =========================================================================
  // Tables Type
  // =========================================================================
  
  describe('Tables type', () => {
    it('should generate Tables type for single table', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('export type Tables = {')
      expect(result).toContain('User: User & Row')
    })
    
    it('should generate Tables type for multiple tables', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Post: {
            name: 'Post',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          },
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('Post: Post')
      expect(result).toContain('User: User & Row')
    })
  })
  
  // =========================================================================
  // Schema Object
  // =========================================================================
  
  describe('schema object', () => {
    it('should generate schema with table columns', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [
              { name: 'id', type: 'string', optional: false, attributes: [] },
              { name: 'email', type: 'string', optional: false, attributes: [] },
              { name: 'name', type: 'string', optional: true, attributes: [] }
            ],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('export const schema = {')
      expect(result).toContain('tables: {')
      expect(result).toContain("User: { columns: ['id', 'email', 'name'] as const }")
    })
    
    it('should generate schema for multiple tables', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Post: {
            name: 'Post',
            fields: [
              { name: 'id', type: 'number', optional: false, attributes: [] },
              { name: 'title', type: 'string', optional: false, attributes: [] }
            ],
            blockAttributes: []
          },
          User: {
            name: 'User',
            fields: [
              { name: 'id', type: 'string', optional: false, attributes: [] },
              { name: 'email', type: 'string', optional: false, attributes: [] }
            ],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain("Post: { columns: ['id', 'title'] as const }")
      expect(result).toContain("User: { columns: ['id', 'email'] as const }")
    })
    
    it('should include as const assertion on schema', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('} as const')
    })
  })
  
  // =========================================================================
  // createDB Function
  // =========================================================================
  
  describe('createDB function', () => {
    it('should generate createDB factory function', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('export function createDB(stores: {')
      expect(result).toContain('User: DataStore<User & Row>')
    })
    
    it('should include DataStore import', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain("import { createSheetsDB, MockAdapter, DataStore, Row } from '@gsquery/core'")
    })
    
    it('should generate createDB with correct return statement', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('return createSheetsDB<Tables>({')
      expect(result).toContain('config: schema,')
      expect(result).toContain('stores')
    })
  })
  
  // =========================================================================
  // createTestDB Function
  // =========================================================================
  
  describe('createTestDB function', () => {
    it('should generate createTestDB helper', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('export function createTestDB()')
    })
    
    it('should create MockAdapter for each table', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Post: {
            name: 'Post',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          },
          User: {
            name: 'User',
            fields: [{ name: 'id', type: 'string', optional: false, attributes: [] }],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      expect(result).toContain('Post: new MockAdapter<Post & Row>()')
      expect(result).toContain('User: new MockAdapter<User & Row>()')
    })
  })
  
  // =========================================================================
  // Integration Tests
  // =========================================================================
  
  describe('integration', () => {
    it('should generate complete client code', () => {
      const ast: SchemaAST = {
        enums: {
          Role: { name: 'Role', values: ['USER', 'ADMIN'] }
        },
        tables: {
          User: {
            name: 'User',
            fields: [
              { name: 'id', type: 'number', optional: false, attributes: [] },
              { name: 'email', type: 'string', optional: false, attributes: [] },
              { name: 'name', type: 'string', optional: true, attributes: [] },
              { name: 'role', type: 'Role', optional: false, attributes: [] }
            ],
            blockAttributes: []
          },
          Post: {
            name: 'Post',
            fields: [
              { name: 'id', type: 'number', optional: false, attributes: [] },
              { name: 'title', type: 'string', optional: false, attributes: [] },
              { name: 'content', type: 'string', optional: false, attributes: [] },
              { name: 'authorId', type: 'number', optional: false, attributes: [] }
            ],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      // Header
      expect(result).toContain('// Auto-generated by gsquery - DO NOT EDIT')
      
      // Imports
      expect(result).toContain("import { createSheetsDB, MockAdapter, DataStore, Row } from '@gsquery/core'")
      expect(result).toContain("import type { Post, User } from './types.js'")
      
      // Tables type
      expect(result).toContain('export type Tables = {')
      expect(result).toContain('Post: Post')
      expect(result).toContain('User: User & Row')
      
      // Schema
      expect(result).toContain('export const schema = {')
      expect(result).toContain("Post: { columns: ['id', 'title', 'content', 'authorId'] as const }")
      expect(result).toContain("User: { columns: ['id', 'email', 'name', 'role'] as const }")
      
      // createDB
      expect(result).toContain('export function createDB(stores: {')
      expect(result).toContain('Post: DataStore<Post & Row>')
      expect(result).toContain('User: DataStore<User & Row>')
      
      // createTestDB
      expect(result).toContain('export function createTestDB()')
      expect(result).toContain('Post: new MockAdapter<Post & Row>()')
      expect(result).toContain('User: new MockAdapter<User & Row>()')
    })
    
    it('should produce syntactically valid TypeScript', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: {
            name: 'User',
            fields: [
              { name: 'id', type: 'number', optional: false, attributes: [] },
              { name: 'email', type: 'string', optional: false, attributes: [] }
            ],
            blockAttributes: []
          }
        }
      }
      
      const result = generateClient(ast)
      
      // Check balanced braces
      const openBraces = (result.match(/{/g) || []).length
      const closeBraces = (result.match(/}/g) || []).length
      expect(openBraces).toBe(closeBraces)
      
      // Check balanced parentheses
      const openParens = (result.match(/\(/g) || []).length
      const closeParens = (result.match(/\)/g) || []).length
      expect(openParens).toBe(closeParens)
    })
  })
})
