/**
 * ERD Generator Tests
 *
 * Issue #224
 */

import { describe, it, expect } from 'vitest'
import { generateErd } from '../../src/generator/erd-generator.js'
import type { SchemaAST, FieldAST, TableAST } from '../../src/parser/types.js'

// =============================================================================
// Fixture Helpers
// =============================================================================

function field(
  name: string,
  type: string,
  optional = false,
  attributes: FieldAST['attributes'] = []
): FieldAST {
  return { name, type, optional, attributes }
}

function idField(type = 'number'): FieldAST {
  return field('id', type, false, [{ name: 'id', args: [] }])
}

function table(name: string, fields: FieldAST[], extra: Partial<TableAST> = {}): TableAST {
  return { name, fields, blockAttributes: [], ...extra }
}

/** User(id) <- Source.<fkName> with the given field shape. */
function relationSchema(fk: FieldAST): SchemaAST {
  return {
    enums: {},
    tables: {
      User: table('User', [idField()]),
      Task: table('Task', [idField(), fk]),
    },
  }
}

const REL = (target: string) => ({ name: 'relation' as const, args: [target] })

describe('generateErd', () => {
  // =========================================================================
  // Document Shape
  // =========================================================================

  describe('document shape', () => {
    it('should include the auto-generated marker', () => {
      const result = generateErd({ enums: {}, tables: {} })

      expect(result.diagram).toContain('Auto-generated by gsquery - DO NOT EDIT')
    })

    it('should wrap the diagram in a mermaid code fence', () => {
      const result = generateErd({ enums: {}, tables: {} })

      expect(result.diagram).toContain('```mermaid')
      expect(result.diagram).toContain('erDiagram')
      expect(result.diagram.trimEnd().endsWith('```')).toBe(true)
    })

    it('should emit entities before relationships', () => {
      const ast = relationSchema(field('assigneeId', 'number', false, [REL('User')]))
      const result = generateErd(ast)

      const entityAt = result.diagram.indexOf('Task {')
      const relationAt = result.diagram.indexOf('User ||--o{ Task')

      expect(entityAt).toBeGreaterThan(-1)
      expect(relationAt).toBeGreaterThan(entityAt)
    })

    it('should keep tables in schema declaration order', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Zebra: table('Zebra', [idField()]),
          Apple: table('Apple', [idField()]),
        },
      }
      const result = generateErd(ast)

      expect(result.diagram.indexOf('Zebra {')).toBeLessThan(result.diagram.indexOf('Apple {'))
    })
  })

  // =========================================================================
  // Attribute Lines
  // =========================================================================

  describe('attribute keys', () => {
    it('should mark the id field PK', () => {
      const ast: SchemaAST = { enums: {}, tables: { User: table('User', [idField()]) } }

      expect(generateErd(ast).diagram).toContain('number id PK')
    })

    it('should mark a field-level @unique field UK', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: table('User', [idField(), field('email', 'string', false, [{ name: 'unique', args: [] }])]),
        },
      }

      expect(generateErd(ast).diagram).toContain('string email UK')
    })

    it('should mark a @relation field FK', () => {
      const ast = relationSchema(field('assigneeId', 'number', false, [REL('User')]))

      expect(generateErd(ast).diagram).toContain('number assigneeId FK')
    })

    it('should join multiple keys with a comma', () => {
      const ast = relationSchema(
        field('assigneeId', 'number', false, [REL('User'), { name: 'unique', args: [] }])
      )

      expect(generateErd(ast).diagram).toContain('number assigneeId FK, UK')
    })

    it('should not mark composite unique block fields UK', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Label: table('Label', [idField(), field('name', 'string')], {
            blockAttributes: [{ name: 'unique', fields: ['projectId', 'name'] }],
          }),
        },
      }

      expect(generateErd(ast).diagram).toContain('string name\n')
      expect(generateErd(ast).diagram).not.toContain('string name UK')
    })

    it('should not render indexes', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Task: table('Task', [idField(), field('projectId', 'number')], {
            blockAttributes: [{ name: 'index', fields: ['projectId'] }],
          }),
        },
      }

      expect(generateErd(ast).diagram).not.toContain('index')
    })
  })

  describe('attribute comments', () => {
    it('should mark an optional field with ?', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: { User: table('User', [idField(), field('nickname', 'string', true)]) },
      }

      expect(generateErd(ast).diagram).toContain('string nickname "?"')
    })

    it('should list enum values for an enum field', () => {
      const ast: SchemaAST = {
        enums: { Role: { name: 'Role', values: ['USER', 'ADMIN'] } },
        tables: { User: table('User', [idField(), field('role', 'Role')]) },
      }

      expect(generateErd(ast).diagram).toContain('Role role "USER|ADMIN"')
    })

    it('should combine the optional marker with enum values', () => {
      const ast: SchemaAST = {
        enums: { Role: { name: 'Role', values: ['USER', 'ADMIN'] } },
        tables: { User: table('User', [idField(), field('role', 'Role', true)]) },
      }

      expect(generateErd(ast).diagram).toContain('Role role "? USER|ADMIN"')
    })

    it('should omit the comment entirely for a plain required field', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: { User: table('User', [idField(), field('name', 'string')]) },
      }

      expect(generateErd(ast).diagram).toContain('string name\n')
    })

    it('should replace double quotes in enum values so the comment stays closed', () => {
      const ast: SchemaAST = {
        enums: { Weird: { name: 'Weird', values: ['a"b'] } },
        tables: { Row: table('Row', [idField(), field('kind', 'Weird')]) },
      }

      const line = generateErd(ast).diagram
      expect(line).toContain(`Weird kind "a'b"`)
      expect(line).not.toContain('a"b')
    })

    it('should render array types without breaking the attribute line', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: { Row: table('Row', [idField(), field('tags', 'string[]')]) },
      }

      expect(generateErd(ast).diagram).toContain('string[] tags')
    })
  })

  // =========================================================================
  // Entity Naming
  // =========================================================================

  describe('entity naming', () => {
    it('should use the table name', () => {
      const ast: SchemaAST = { enums: {}, tables: { User: table('User', [idField()]) } }

      expect(generateErd(ast).diagram).toContain('User {')
    })

    it('should note the sheet name when the table is mapped', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: { User: table('User', [idField()], { mapTo: 'Users Sheet' }) },
      }
      const result = generateErd(ast)

      expect(result.diagram).toContain('%% User -> sheet "Users Sheet"')
      expect(result.diagram).toContain('User {')
    })

    it('should not emit a sheet comment when the table is unmapped', () => {
      const ast: SchemaAST = { enums: {}, tables: { User: table('User', [idField()]) } }

      expect(generateErd(ast).diagram).not.toContain('sheet')
    })
  })

  // =========================================================================
  // Relationships
  // =========================================================================

  describe('cardinality', () => {
    it('should render a required FK as one-to-many', () => {
      const ast = relationSchema(field('assigneeId', 'number', false, [REL('User')]))

      expect(generateErd(ast).diagram).toContain('User ||--o{ Task : "assigneeId"')
    })

    it('should render an optional FK as zero-or-one to many', () => {
      const ast = relationSchema(field('assigneeId', 'number', true, [REL('User')]))

      expect(generateErd(ast).diagram).toContain('User |o--o{ Task : "assigneeId"')
    })

    it('should render a unique FK as one-to-one', () => {
      const ast = relationSchema(
        field('ownerId', 'number', false, [REL('User'), { name: 'unique', args: [] }])
      )

      expect(generateErd(ast).diagram).toContain('User ||--|| Task : "ownerId"')
    })

    it('should render an array FK as many-to-many', () => {
      const ast = relationSchema(field('watcherIds', 'number[]', false, [REL('User')]))

      expect(generateErd(ast).diagram).toContain('User }o--o{ Task : "watcherIds"')
    })

    it('should let an array FK win over optional', () => {
      const ast = relationSchema(field('watcherIds', 'number[]', true, [REL('User')]))

      expect(generateErd(ast).diagram).toContain('User }o--o{ Task : "watcherIds"')
    })

    it('should let a unique FK win over optional', () => {
      const ast = relationSchema(
        field('ownerId', 'number', true, [REL('User'), { name: 'unique', args: [] }])
      )

      expect(generateErd(ast).diagram).toContain('User ||--|| Task : "ownerId"')
    })
  })

  describe('relationship edges', () => {
    it('should label the edge with the foreign key field name', () => {
      const ast = relationSchema(field('assigneeId', 'number', false, [REL('User')]))

      expect(generateErd(ast).diagram).toContain(': "assigneeId"')
    })

    it('should keep two relations between the same pair distinct', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: table('User', [idField()]),
          Comment: table('Comment', [
            idField(),
            field('authorId', 'number', false, [REL('User')]),
            field('editorId', 'number', true, [REL('User')]),
          ]),
        },
      }
      const result = generateErd(ast)

      expect(result.diagram).toContain('User ||--o{ Comment : "authorId"')
      expect(result.diagram).toContain('User |o--o{ Comment : "editorId"')
      expect(result.relationCount).toBe(2)
    })

    it('should render a self-relation', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          Task: table('Task', [idField(), field('parentId', 'number', true, [REL('Task')])]),
        },
      }

      expect(generateErd(ast).diagram).toContain('Task |o--o{ Task : "parentId"')
    })

    it('should skip a @relation whose target table is not defined', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: { Task: table('Task', [idField(), field('ghostId', 'number', false, [REL('Ghost')])]) },
      }
      const result = generateErd(ast)

      expect(result.relationCount).toBe(0)
      expect(result.diagram).not.toContain('Ghost')
    })
  })

  // =========================================================================
  // relationCount
  // =========================================================================

  describe('relationCount', () => {
    it('should be 0 when no @relation is declared', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: table('User', [idField()]),
          Task: table('Task', [idField(), field('assigneeId', 'number')]),
        },
      }
      const result = generateErd(ast)

      expect(result.relationCount).toBe(0)
      expect(result.diagram).toContain('Task {')
    })

    it('should count every declared relation', () => {
      const ast: SchemaAST = {
        enums: {},
        tables: {
          User: table('User', [idField()]),
          Project: table('Project', [idField(), field('ownerId', 'number', false, [REL('User')])]),
          Task: table('Task', [
            idField(),
            field('projectId', 'number', false, [REL('Project')]),
            field('assigneeId', 'number', true, [REL('User')]),
          ]),
        },
      }

      expect(generateErd(ast).relationCount).toBe(3)
    })
  })
})
