/**
 * Generate Command Tests
 * 
 * Issue #22
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'fs'
import { join } from 'path'
import {
  runGenerate,
  generateIndex,
  resolveGenerateOptions,
  DEFAULT_SCHEMA_FILE,
  DEFAULT_OUTPUT_DIR,
} from '../../src/commands/generate.js'
import type { GSQConfig } from '../../src/commands/init.js'

// =============================================================================
// Test Fixtures
// =============================================================================

const TEST_DIR = join(process.cwd(), 'tests', 'fixtures', 'generate-test')
const SCHEMA_PATH = join(TEST_DIR, 'schema.gsq.yaml')
const OUTPUT_DIR = join(TEST_DIR, 'generated')
const CLIENT_OUTPUT_DIR = join(OUTPUT_DIR, 'client')

const VALID_SCHEMA = `
enums:
  Role:
    - USER
    - ADMIN

tables:
  User:
    fields:
      id: number @id
      email: string @unique
      name: string?
      role: Role
  Post:
    fields:
      id: number @id
      title: string
      content: string
      authorId: number
    indexes:
      - [authorId]
`

const EMPTY_SCHEMA = ''

const INVALID_YAML = `
tables:
  User:
    fields
      id: string
`

// =============================================================================
// Test Helpers
// =============================================================================

function setupTestDir(): void {
  if (existsSync(TEST_DIR)) {
    rmSync(TEST_DIR, { recursive: true })
  }
  mkdirSync(TEST_DIR, { recursive: true })
}

function cleanupTestDir(): void {
  if (existsSync(TEST_DIR)) {
    rmSync(TEST_DIR, { recursive: true })
  }
}

function writeSchema(content: string): void {
  writeFileSync(SCHEMA_PATH, content, 'utf-8')
}

// =============================================================================
// Tests
// =============================================================================

describe('generateIndex', () => {
  it('should generate index.ts content with re-exports', () => {
    const result = generateIndex()

    expect(result).toContain('// Auto-generated by gsquery - DO NOT EDIT')
    expect(result).toContain("export * from './types.js'")
    expect(result).toContain("export * from './client.js'")
  })
})

describe('runGenerate', () => {
  beforeEach(() => {
    setupTestDir()
  })
  
  afterEach(() => {
    cleanupTestDir()
  })
  
  // =========================================================================
  // Success Cases
  // =========================================================================
  
  describe('success cases', () => {
    it('should generate all three files from valid schema', async () => {
      writeSchema(VALID_SCHEMA)
      
      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      expect(result.success).toBe(true)
      expect(result.files).toContain('types.ts')
      expect(result.files).toContain('client.ts')
      expect(result.files).toContain('index.ts')
      expect(result.errors).toHaveLength(0)
    })
    
    it('should create output directory if it does not exist', async () => {
      writeSchema(VALID_SCHEMA)
      
      expect(existsSync(OUTPUT_DIR)).toBe(false)
      
      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      expect(existsSync(OUTPUT_DIR)).toBe(true)
    })
    
    it('should generate valid types.ts content', async () => {
      writeSchema(VALID_SCHEMA)
      
      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      const typesContent = readFileSync(join(OUTPUT_DIR, 'types.ts'), 'utf-8')
      
      expect(typesContent).toContain('// Auto-generated by gsquery - DO NOT EDIT')
      expect(typesContent).toContain("export type Role = 'USER' | 'ADMIN'")
      expect(typesContent).toContain('export interface User {')
      expect(typesContent).toContain('export interface Post {')
    })
    
    it('should generate valid client.ts content', async () => {
      writeSchema(VALID_SCHEMA)
      
      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      const clientContent = readFileSync(join(OUTPUT_DIR, 'client.ts'), 'utf-8')
      
      expect(clientContent).toContain('// Auto-generated by gsquery - DO NOT EDIT')
      expect(clientContent).toContain("import { createSheetsDB")
      expect(clientContent).toContain('export type Tables = {')
      expect(clientContent).toContain('export const schema = {')
      expect(clientContent).toContain('export function createDB')
      expect(clientContent).toContain('export function createTestDB')
    })
    
    it('should generate valid index.ts content', async () => {
      writeSchema(VALID_SCHEMA)
      
      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      const indexContent = readFileSync(join(OUTPUT_DIR, 'index.ts'), 'utf-8')

      expect(indexContent).toContain("export * from './types.js'")
      expect(indexContent).toContain("export * from './client.js'")
    })
    
    it('should handle empty schema', async () => {
      writeSchema(EMPTY_SCHEMA)
      
      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      expect(result.success).toBe(true)
      expect(result.files).toHaveLength(3)
    })
  })
  
  // =========================================================================
  // Error Cases
  // =========================================================================
  
  describe('error cases', () => {
    it('should fail when schema file does not exist', async () => {
      const result = await runGenerate({
        schema: join(TEST_DIR, 'nonexistent.yaml'),
        output: OUTPUT_DIR,
      })
      
      expect(result.success).toBe(false)
      expect(result.errors[0]).toContain('Schema file not found')
    })
    
    it('should fail when schema has invalid YAML', async () => {
      writeSchema(INVALID_YAML)
      
      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })
      
      expect(result.success).toBe(false)
      expect(result.errors[0]).toContain('YAML parse error')
    })
  })
  
  // =========================================================================
  // Options
  // =========================================================================

  describe('options', () => {
    it('should use provided schema path', async () => {
      const customPath = join(TEST_DIR, 'custom-schema.yaml')
      writeFileSync(customPath, VALID_SCHEMA, 'utf-8')

      const result = await runGenerate({
        schema: customPath,
        output: OUTPUT_DIR,
      })

      expect(result.success).toBe(true)
    })

    it('should use provided output directory', async () => {
      writeSchema(VALID_SCHEMA)
      const customOutput = join(TEST_DIR, 'custom-output')

      await runGenerate({
        schema: SCHEMA_PATH,
        output: customOutput,
      })

      expect(existsSync(join(customOutput, 'types.ts'))).toBe(true)
      expect(existsSync(join(customOutput, 'client.ts'))).toBe(true)
      expect(existsSync(join(customOutput, 'index.ts'))).toBe(true)
    })

  })

  // =========================================================================
  // Client Output (Issue #133)
  // =========================================================================

  describe('--client output', () => {
    it('should write the typed client into <output>/client by default', async () => {
      writeSchema(VALID_SCHEMA)

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        client: true,
      })

      expect(result.success).toBe(true)
      expect(result.warnings).toHaveLength(0)
      expect(existsSync(join(CLIENT_OUTPUT_DIR, 'types.ts'))).toBe(true)
      expect(existsSync(join(CLIENT_OUTPUT_DIR, 'client.ts'))).toBe(true)
      expect(existsSync(join(CLIENT_OUTPUT_DIR, 'index.ts'))).toBe(true)
    })

    it('should honor an explicit client output directory', async () => {
      writeSchema(VALID_SCHEMA)
      const customClientDir = join(TEST_DIR, 'src', 'db')

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        clientOutput: customClientDir,
        client: true,
      })

      expect(result.success).toBe(true)
      expect(existsSync(join(customClientDir, 'client.ts'))).toBe(true)
      expect(existsSync(join(CLIENT_OUTPUT_DIR, 'client.ts'))).toBe(false)
    })

    it('should never write into node_modules', async () => {
      writeSchema(VALID_SCHEMA)

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        client: true,
      })

      for (const file of result.files) {
        expect(file).not.toContain('node_modules')
        expect(file).not.toContain('@gsquery/client')
      }
      expect(existsSync(join(process.cwd(), 'node_modules', '@gsquery', 'client', 'generated'))).toBe(
        false
      )
    })

    it('should generate client code with relative imports only', async () => {
      writeSchema(VALID_SCHEMA)

      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        client: true,
      })

      const clientContent = readFileSync(join(CLIENT_OUTPUT_DIR, 'client.ts'), 'utf-8')
      const indexContent = readFileSync(join(CLIENT_OUTPUT_DIR, 'index.ts'), 'utf-8')

      expect(clientContent).toContain("import type { Tables } from './types.js'")
      expect(clientContent).not.toContain('@gsquery/client/generated')
      expect(indexContent).not.toContain('@gsquery/client/generated')
    })

    it('should report the client output directory relative to the project', async () => {
      writeSchema(VALID_SCHEMA)

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        client: true,
      })

      expect(result.files.some(f => f.endsWith('generated/client'))).toBe(true)
    })

    it('should not create client files when --client is omitted', async () => {
      writeSchema(VALID_SCHEMA)

      await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })

      expect(existsSync(CLIENT_OUTPUT_DIR)).toBe(false)
    })
  })

  // =========================================================================
  // Overwrite Protection (Issue #133)
  // =========================================================================

  describe('overwrite protection', () => {
    it('should refuse to overwrite a file without the auto-generated header', async () => {
      writeSchema(VALID_SCHEMA)
      mkdirSync(OUTPUT_DIR, { recursive: true })
      const handWritten = 'export const mine = 1\n'
      writeFileSync(join(OUTPUT_DIR, 'types.ts'), handWritten, 'utf-8')

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
      })

      expect(result.success).toBe(false)
      expect(result.errors[0]).toContain('Refusing to overwrite')
      expect(result.errors[0]).toContain('--force')
      expect(readFileSync(join(OUTPUT_DIR, 'types.ts'), 'utf-8')).toBe(handWritten)
      // No partial writes
      expect(existsSync(join(OUTPUT_DIR, 'client.ts'))).toBe(false)
    })

    it('should overwrite an unprotected file when --force is passed', async () => {
      writeSchema(VALID_SCHEMA)
      mkdirSync(OUTPUT_DIR, { recursive: true })
      writeFileSync(join(OUTPUT_DIR, 'types.ts'), 'export const mine = 1\n', 'utf-8')

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        force: true,
      })

      expect(result.success).toBe(true)
      expect(readFileSync(join(OUTPUT_DIR, 'types.ts'), 'utf-8')).toContain(
        'Auto-generated by gsquery'
      )
    })

    it('should overwrite previously generated files without --force', async () => {
      writeSchema(VALID_SCHEMA)

      const first = await runGenerate({ schema: SCHEMA_PATH, output: OUTPUT_DIR, client: true })
      expect(first.success).toBe(true)

      const second = await runGenerate({ schema: SCHEMA_PATH, output: OUTPUT_DIR, client: true })
      expect(second.success).toBe(true)
      expect(second.errors).toHaveLength(0)
    })

    it('should protect hand-written files in the client output directory', async () => {
      writeSchema(VALID_SCHEMA)
      mkdirSync(CLIENT_OUTPUT_DIR, { recursive: true })
      writeFileSync(join(CLIENT_OUTPUT_DIR, 'client.ts'), 'export const mine = 1\n', 'utf-8')

      const result = await runGenerate({
        schema: SCHEMA_PATH,
        output: OUTPUT_DIR,
        client: true,
      })

      expect(result.success).toBe(false)
      expect(result.errors[0]).toContain('Refusing to overwrite')
    })
  })
})

// =============================================================================
// Option Resolution (Issue #133)
// =============================================================================

describe('resolveGenerateOptions', () => {
  const fullConfig: GSQConfig = {
    spreadsheetId: 'sheet-id',
    migrationsDir: 'migrations',
    generatedDir: 'src/generated',
    schemaFile: 'db/schema.gsq.yaml',
    clientDir: 'src/db/client',
  }

  it('should fall back to built-in defaults without config or flags', () => {
    const resolved = resolveGenerateOptions({}, null)

    expect(resolved.schema).toBe(DEFAULT_SCHEMA_FILE)
    expect(resolved.output).toBe(DEFAULT_OUTPUT_DIR)
    expect(resolved.clientOutput).toBe(join(DEFAULT_OUTPUT_DIR, 'client'))
  })

  it('should use config values when no flags are passed', () => {
    const resolved = resolveGenerateOptions({}, fullConfig)

    expect(resolved.schema).toBe('db/schema.gsq.yaml')
    expect(resolved.output).toBe('src/generated')
    expect(resolved.clientOutput).toBe('src/db/client')
  })

  it('should prefer CLI flags over config values', () => {
    const resolved = resolveGenerateOptions(
      { schema: 'other.yaml', output: 'out', clientOutput: 'out/typed' },
      fullConfig
    )

    expect(resolved.schema).toBe('other.yaml')
    expect(resolved.output).toBe('out')
    expect(resolved.clientOutput).toBe('out/typed')
  })

  it('should derive the client output from the resolved output directory', () => {
    const resolved = resolveGenerateOptions({ output: 'src/generated' }, null)

    expect(resolved.clientOutput).toBe(join('src/generated', 'client'))
  })

  it('should derive the client output from the config generatedDir', () => {
    const config: GSQConfig = { ...fullConfig, clientDir: undefined }
    const resolved = resolveGenerateOptions({}, config)

    expect(resolved.clientOutput).toBe(join('src/generated', 'client'))
  })

  it('should ignore empty config values', () => {
    const config: GSQConfig = {
      spreadsheetId: '',
      migrationsDir: '',
      generatedDir: '',
      schemaFile: '',
    }
    const resolved = resolveGenerateOptions({}, config)

    expect(resolved.schema).toBe(DEFAULT_SCHEMA_FILE)
    expect(resolved.output).toBe(DEFAULT_OUTPUT_DIR)
  })

  it('should pass through boolean flags', () => {
    const resolved = resolveGenerateOptions({ watch: true, client: true, force: true }, null)

    expect(resolved.watch).toBe(true)
    expect(resolved.client).toBe(true)
    expect(resolved.force).toBe(true)
  })
})
